Repository RyanWri/data-science2-lab-final-project, pull requests merged in 2024-09, with the labels that each got.

#32 team_7/task_5
  src/team_7/task_5/hospitalization1.xlsx
  src/team_7/task_5/task_5.py
  src/team_7/task_5/task_5_notebook.ipynb
Labels: enhancement

#53 Team 7/task 23
  src/team_7/task_23/task_23.py
  src/team_7/task_23/task_23_notebook.ipynb
  src/team_7/task_5/task_5.py
Labels: enhancement

#54 Team 1 - Task 9 Generic EDA + hospitalization1 csv
  src/data/hospitalization1.csv
  src/team_1/conclusion.md
  src/team_1/task_24/patient_stas.py
  src/team_1/task_24/task_24.py
  src/team_1/task_9/generic_eda.py
  src/team_1/task_9/task_9.py
  src/team_1/team_1_results.ipynb
  src/team_1/translations/hospitalization1.json
  src/team_1/translations/unitsOccupancyRate.json
  src/team_1/utils.py
Labels: documentation, enhancement

#35 Team 09: Format fix #task_06
  .gitignore
  src/team_9/README.md
  src/team_9/assets/erBeforeHospitalization.csv
  src/team_9/main.py
  src/team_9/src_code/__init__.py
  src/team_9/src_code/excel/utils.py
Labels: enhancement

#56 Team1-Task26 Rehospitalization NN model
  src/team_1/hospital_models/__init.py
  src/team_1/hospital_models/generic_torch_model.py
  src/team_1/task_24/patient_stas.py
  src/team_1/task_26/__init__.py
  src/team_1/task_26/age_to_gender_model.py
  src/team_1/task_26/rehospital_model.py
  src/team_1/team_1_results.ipynb
  src/team_1/translations/GeneralData.json
Labels: enhancement

#49 Team2 task20 patch1
  src/team_2/README.md
  src/team_2/task_20/task_20.py
  src/team_2/task_9/task_9.py
  src/team_2/team_2_results.ipynb
  src/team_2/translations/hDoctor_columns.json
  src/team_2/translations/release_Doctors_columns.json
Labels: help wanted

#68 Team_7/Task_23: Updated Script + NoteBook
  src/team_7/task_23/task_23.py
  src/team_7/task_23/task_23_notebook.ipynb
Labels: enhancement

#72 Create New DataSet
  src/team_7/task_23/hospitalization2_cleaned.xlsx
  src/team_7/task_23/task_23.py
Labels: documentation

#67 Team 1 - Task 46
  src/team_1/task_37/pca_model.py
  src/team_1/task_37/task_37.py
  src/team_1/team_1_results.ipynb
  src/team_1/utils.py
Labels: documentation

#76 Team_7/Task_39 : Dimensionality Reduction for erBeforeHospitalization2 DataSet
  src/team_7/task_23/hospitalization2_cleaned.xlsx
  src/team_7/task_39/task_39.py
  src/team_7/task_39/task_39_notebook.ipynb
Labels: enhancement

#78 Team_7/Taks_43 : Literature Review Draft
  src/team_7/task_43/Literature Review.docx
Labels: enhancement

#83 Team 7 - Task 29
  src/.DS_Store
  src/team_7/.DS_Store
  src/team_7/task29/task_29_dataset_final.xlsx
  src/team_7/task29/task_29_dataset_prep.py
  src/team_7/task29/task_29_model.py
  src/team_7/task29/task_29_results.ipynb
Labels: documentation, enhancement

#85 Team 7 - Minor fixes
  .DS_Store
  src/.DS_Store
  src/team_7/.DS_Store
  src/team_7/task29/merged_hospitalization_with_medication.xlsx
  src/team_7/task29/task29_visual.py
  src/team_7/task29/task_29_dataset.xlsx
  src/team_7/task29/task_29_results.ipynb
Labels: enhancement

#95 Team 7/task 43 : Clean Unnecessary Files
  src/team_7/team_7_notebook.ipynb
Labels: documentation, enhancement

#43 Team 09: Minor fixes and task 31 (#task_31)
  src/team_9/README.md
  src/team_9/assets/hospitalization_timeseries_analysis_by_month.png
  src/team_9/assets/team_09_task_06_erBeforeHospitalization.csv
  src/team_9/assets/team_09_task_22.md
  src/team_9/assets/team_09_task_31.md
  src/team_9/main.py
  src/team_9/src_code/__init__.py
  src/team_9/src_code/exploratory_data_analysis/eda.py
Labels: enhancement
